### ISSUE TITLE
This clover is also able to boot Catalina with updated clover

### ISSUE THREAD

**Issue by Sciroccogti** [xiaoxx970/Hackintosh-Mojave-for-Lenovo-Yoga710#2]
I replaced `clover.efi` with a v4940 one, and I installed Catalina successfully.

**Comment by xiaoxx970** [comment]
Thank you for reply, I have also updated to Catalina successfully in past few days. And now I got my sleep working by add kernel flags `bpr_initialdelay=400 bpr_preresetdelay=0 bpr_postresetdelay=400`. 
But after update my WIFI can only find 2.4G signal, that's what I'm dealing with now.
Oh.. also, Bluetooth not working after awake.

**Comment by Sciroccogti** [comment]
I'm gonna close this issue, but maybe you can pin it so that more people can see it.
